SRC_PATH = ../src/test/java
PACKAGE = info.thinkmore.android.dbhelper
$(SRC_PATH)/info/thinkmore/android/dbhelper/TestTable.java : test_schema.rb
	android_dbhelper_generator $(SRC_PATH) $(PACKAGE) test_schema.rb
