SRC_PATH = ../src/test/java
PACKAGE = info.thinkmore.android.dbhelper.test
$(SRC_PATH)/test/java/info/thinkmore/android/dbhelper/test/TestTable.java : test_schema.rb
../src/test/java/info/thinkmore/android/dbhelper/test/TestTable.java : test_schema.rb
	android_dbhelper_generator $(SRC_PATH) $(PACKAGE) test_schema.rb
